server:
  port: 8000 #서버가 사용할 포트번호
  servlet:
    context-path: /api #API 기본설정
    encoding:
      charset: UTF-8 # 서버에서 사용하는 문자 인코딩(UTF-8로 설정해 다국어 지원)
      enabled: true #문자인고킹 기능 활성화
      force: true # 응답 헤더에 강제로 UTF-8 인코딩 적용하도록 강제

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 182074
    url: jdbc:mysql://localhost:3306/workout?serverTimezone=Asia/Seoul

mybatis:
  mapper-locations: classpath:mappers/mysql/**/*.xml
